BEGIN;
GRANT SELECT ON users, patient_profiles, sessions TO saydaliyati_app;
GRANT INSERT (email, phone, password_hash) ON users TO saydaliyati_app;
GRANT UPDATE (last_login_at, updated_at) ON users TO saydaliyati_app;
GRANT INSERT ON patient_profiles, sessions, audit_logs TO saydaliyati_app;
GRANT UPDATE (first_name, last_name, preferred_language, timezone, updated_at) ON patient_profiles TO saydaliyati_app;
GRANT UPDATE (refresh_token_hash, last_used_at, revoked_at) ON sessions TO saydaliyati_app;
GRANT SELECT ON manufacturers, medicines, active_ingredients, medicine_ingredients, medicine_barcodes, medicine_images TO saydaliyati_app;
GRANT SELECT ON medication_inventory TO saydaliyati_app;
GRANT INSERT (patient_id, medicine_id, quantity, unit, batch_number, expiry_date, purchase_date, storage_location, source, low_stock_threshold, notes) ON medication_inventory TO saydaliyati_app;
GRANT UPDATE (quantity, unit, batch_number, expiry_date, purchase_date, storage_location, source, low_stock_threshold, notes, archived_at, updated_at) ON medication_inventory TO saydaliyati_app;
GRANT SELECT ON prescriptions, prescription_medications, prescription_extracted_fields TO saydaliyati_app;
GRANT INSERT (patient_id, prescription_date, valid_until, source) ON prescriptions TO saydaliyati_app;
GRANT UPDATE (status, updated_at) ON prescriptions TO saydaliyati_app;
GRANT INSERT (prescription_id, medicine_id, extracted_name, dosage, dosage_unit, frequency, frequency_unit, duration, duration_unit, quantity, instructions, updated_at) ON prescription_medications TO saydaliyati_app;
GRANT UPDATE (medicine_id, extracted_name, dosage, dosage_unit, frequency, frequency_unit, duration, duration_unit, quantity, instructions, confirmation_status, updated_at) ON prescription_medications TO saydaliyati_app;
GRANT INSERT ON prescription_extracted_fields TO saydaliyati_app;
GRANT SELECT (id, prescription_id, patient_id, page_number, storage_key, mime_type, processing_status, created_at, deleted_at, retention_until) ON prescription_documents TO saydaliyati_app;
GRANT INSERT (id, prescription_id, patient_id, page_number, storage_key, mime_type, processing_status) ON prescription_documents TO saydaliyati_app;
GRANT SELECT ON notification_preferences TO saydaliyati_app;
GRANT INSERT (user_id, dose_reminders, expiry_reminders, low_stock_alerts, sharing_notifications, system_notifications, expiry_lead_days) ON notification_preferences TO saydaliyati_app;
GRANT UPDATE (dose_reminders, expiry_reminders, low_stock_alerts, sharing_notifications, system_notifications, expiry_lead_days, updated_at) ON notification_preferences TO saydaliyati_app;
GRANT SELECT ON treatments, treatment_medications, medication_schedules, medication_occurrences, medication_events TO saydaliyati_app;
GRANT INSERT (patient_id, prescription_id, name, start_date, end_date) ON treatments TO saydaliyati_app;
GRANT UPDATE (status, activated_at, updated_at) ON treatments TO saydaliyati_app;
GRANT INSERT (treatment_id, medicine_id, dose, dose_unit, schedule_type, instructions) ON treatment_medications TO saydaliyati_app;
GRANT INSERT (treatment_medication_id, time, timezone, days_of_week, start_date, end_date) ON medication_schedules TO saydaliyati_app;
GRANT INSERT ON medication_occurrences TO saydaliyati_app;
GRANT INSERT (occurrence_id, patient_id, treatment_medication_id, scheduled_at, status, notes) ON medication_events TO saydaliyati_app;
GRANT SELECT ON notifications TO saydaliyati_app;
GRANT INSERT (user_id, occurrence_id, type, title, body, data) ON notifications TO saydaliyati_app;
GRANT UPDATE (read_at) ON notifications TO saydaliyati_app;
GRANT SELECT, INSERT, UPDATE ON admin_directory_entries, admin_settings TO saydaliyati_app;
GRANT UPDATE (status) ON users TO saydaliyati_app;
GRANT INSERT (name, normalized_name, generic_name, strength, dosage_form, status, source, updated_at) ON medicines TO saydaliyati_app;
GRANT UPDATE (name, normalized_name, generic_name, strength, dosage_form, status, source, updated_at) ON medicines TO saydaliyati_app;
GRANT SELECT, INSERT ON admin_transfer_receipts TO saydaliyati_app;
COMMIT;
